build: New PR patch method added
Signed-off-by: Eliminater74 <eliminater74@gmail.com>

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -46,6 +46,8 @@ env:
   USE_CUST_THEMES: true
   USE_CUSTOM_CONFIGURATION: true
   USE_OPENWRT_PATCHES: true
+  USE_PR_OPENWRT_PATCHES_NEW: false
+  USE_PR_OPENWRT_PATCHES_PACKAGES_NEW: false
   USE_PR_OPENWRT_PATCHES: false
   USE_PR_OPENWRT_PATCHES_PACKAGES: false
   USE_DEVOPENWRT: true
@@ -309,6 +311,40 @@ jobs:
         run: |
           echo "Error: $?"
           echo "[*] 'git am patch' FAILED."
+          git am --abort
+### ----------------------------------------------------------------- ###
+      - name: Pull Request OpenWRT Patches (OpenWRT)
+        id: PROPNEW
+        continue-on-error: true
+        if: env.USE_PR_OPENWRT_PATCHES_NEW == 'true' && !cancelled()
+        run: |
+          chmod +x scripts/$FUNCTIONS_SH
+          source scripts/$FUNCTIONS_SH
+          cd openwrt
+          APPLY_PR_PATCHES_NEW
+### --------------------------- ###
+      - name: If Error (PR Patches Main)
+        if: steps.PROPNEW.outcome == 'failure'
+        run: |
+          echo "Error: $?"
+          echo "[*] 'git am $line.patch' FAILED."
+          git am --abort
+### ----------------------------------------------------------------- ###
+      - name: Pull Request OpenWRT Packages Patches (Packages)
+        id: PROPPNEW
+        continue-on-error: true
+        if: env.USE_PR_OPENWRT_PATCHES_PACKAGES_NEW == 'true' && !cancelled()
+        run: |
+          chmod +x scripts/$FUNCTIONS_SH
+          source scripts/$FUNCTIONS_SH
+          cd openwrt
+          APPLY_PR_PATCHES_PACKAGES_NEW
+### --------------------------- ###
+      - name: If Error (PR Patches Packages)
+        if: steps.PROPPNEW.outcome == 'failure'
+        run: |
+          echo "Error: $?"
+          echo "[*] 'git am $line.patch' FAILED."
           git am --abort
 ### ----------------------------------------------------------------- ###
       - name: Pull Request OpenWRT Patches (OpenWRT)
